# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Nelson Ochoa
email: nelsonochoam@gmail.com
description: > # Nelson Ochoa
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://nelsonochoam.com" # the base hostname & protocol for your site
github_username:  nelsonochoam
linkedin_username: nelsonochoam

# Build settings
markdown: kramdown
