# Site settings
title: Nelson Ochoa
email: nelsonochoam@gmail.com
description: > # Nelson Ochoa
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://nelsonochoam.com" # the base hostname & protocol for your site
github_username:  nelsonochoam
linkedin_username: nelsonochoam

# Build settings
markdown: kramdown
